name: om_vimeo_player
description: This package provide 1 fucntions. First is getting vimeo resource data.
version: 0.0.1
homepage: https://github.com/omarnasser199789/om_vimeo_player
repository: https://github.com/omarnasser199789/om_vimeo_player

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  # video player
  video_player: ^2.9.2
  chewie: ^1.8.5

  # http
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
